### ISSUE TITLE
Request for your paper

### ISSUE THREAD

**Issue by John2016** [sjtrny/kssc#1]
Hi

I'm a Ph.D candidate in China

I‘m very interested in this ksss work, I think this idea is so brilliant

And I want to read your paper in detail while I found this paper is not available through Google

So may I ask for your manuscript for this "ksss" work to get a deeper understanding of it

Thank you !

Best wishes !

Yuan

**Comment by sjtrny** [comment]
@John2016 Thanks for your interest. I will release it on arxiv and reply again when it is uploaded.

**Comment by sjtrny** [comment]
@John2016 Here you go https://arxiv.org/abs/1704.03958

**Comment by John2016** [comment]
@sjtrny Thank you!
